/**
 * Branded entity identifiers.
 *
 * Every id in Dukaano is a UUIDv7 generated by whichever side creates the row — including the
 * offline client (blueprint §14.3). v7 rather than v4 because it is time-ordered: SQLite and
 * Postgres B-tree inserts stay sequential instead of scattering across the index, which matters
 * on a 2 GB Android device with a 20,000-row sales table.
 *
 * The brands are type-level only. They exist because `saleId` and `customerId` are both strings,
 * and passing one where the other belongs is otherwise invisible to the compiler — in a codebase
 * where that mistake means charging the wrong customer.
 */
declare const idBrand: unique symbol

type Id<TName extends string> = string & { readonly [idBrand]: TName }

export type ShopId = Id<'Shop'>
export type UserId = Id<'User'>
export type MembershipId = Id<'ShopMembership'>
export type DeviceId = Id<'Device'>
export type SessionId = Id<'Session'>
export type CategoryId = Id<'Category'>
export type ProductId = Id<'Product'>
export type CustomerId = Id<'Customer'>
export type SupplierId = Id<'Supplier'>
export type SaleId = Id<'Sale'>
export type SaleItemId = Id<'SaleItem'>
export type PaymentId = Id<'Payment'>
export type LedgerEntryId = Id<'CustomerLedgerEntry'>
export type InventoryTransactionId = Id<'InventoryTransaction'>
export type PurchaseId = Id<'Purchase'>
export type MessageId = Id<'Message'>
export type SubscriptionId = Id<'Subscription'>
export type PlanId = Id<'Plan'>
export type AuditLogId = Id<'AuditLog'>
/** The idempotency key carried by every offline-creatable mutation (blueprint §14.4). */
export type OperationId = Id<'Operation'>

/** RFC 9562 UUID, any version. Accepts the nil UUID; rejects braces and urn: prefixes. */
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

export function isUuid(value: unknown): value is string {
  return typeof value === 'string' && UUID_PATTERN.test(value)
}

/**
 * Brand a validated UUID string as a typed id.
 *
 * Call this at trust boundaries only — a DB row, a validated request body, a sync payload that
 * has already been through Zod. It does not re-validate, because doing so on every internal
 * function call would cost more than it catches.
 */
export function asId<T extends string>(value: string): Id<T> {
  return value as Id<T>
}

/** Validating constructor for untrusted input. Throws on a malformed UUID. */
export function parseId<T extends string>(value: unknown, entity: string): Id<T> {
  if (!isUuid(value)) {
    throw new TypeError(`Expected a UUID for ${entity}, received: ${JSON.stringify(value)}`)
  }
  return value as Id<T>
}
